### PR TITLE
Workaround for faulty bootloader in GD32V

### PR DESCRIPTION
**Pull request by elfmimi**
Fix issue #5 .

If anyone else has the chip with supposedly the same revision, please try this.

### CODE REVIEW

**Comment by ghj1453** [comment]
Thanks to your pull request, I can download bin in linux os.
If i use this command  with leave
"sudo dfu-util -s 0x08000000:leave -D led.bin"
then function is ok.
But there is a report:
"dfu-util: Error during download get_status"

**Comment by elfmimi** [comment]
Please read through issue #5 and let me know what it looks when you do dfu-util --list.

I suppose we can add some conditions to select whether to use workaround. That's why this is a draft.
@ghj1453

**Comment by ghj1453** [comment]
When I exec  dfu-util -l,  the info is 
Found DFU: [28e9:0189] ver=0100, devnum=5, cfg=1, intf=0, path="2-1.2", alt=0, name="@Internal Flash  /0x08000000/128*001Kg", serial="3CBJ"
I guess the bootloader is "version B" which is without alt=1.As you know original gd32-dfu-util don't work well.
I use this pull request version : "sudo dfu-util -s 0x08000000 -D led.bin" .  Everything is ok.
Then I try  "sudo dfu-util -s 0x08000000:leave -D led.bin" Everything is ok also. Download success. CPU LEAVES DFU MODE AUTO.
But sometimes there is a error info in the end of log
 
Downloading to address = 0x08000000, size = 20120
Erase   	[=========================] 100%        20120 bytes
Erase    done.
Download	[=========================] 100%        20120 bytes
Download done.
File downloaded successfully
**dfu-util: Error during download get_status**

**Comment by elfmimi** [comment]
I can confirm that sometimes get_status error occurs after a successful download. But it is also true for unmodified dfu-util and, tentatively called, "version A" bootloader. @ghj1453 
So I consider it as unrelated to this draft patch .  -> refer to https://github.com/riscv-mcu/gd32-dfu-utils/issues/4

**Comment by elfmimi** [comment]
It turned out the very same workaround has already included in the upstream development code base. in 2016!!!
https://sourceforge.net/p/dfu-util/dfu-util/ci/740858264113140aeb8f1504abb59f9140acba9d/

Even surprising is that it has never released in 4 years!!!! until the release of dfu-util 0.10 last week, 21st Nov 2020.
https://sourceforge.net/projects/dfu-util/files/

**Comment by elfmimi** [comment]
BTW **dfu-util: Error during download get_status** still persists.

**Pull request closed without merging**
